/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;
import javax.swing.JLabel;
import controller.ClienteController;
import java.util.List;
import model.Cliente;
import model.Conta;

/**
 *
 * @author MR WALLACE
 */
public class LoginView extends javax.swing.JFrame {

    private ClienteController clienteController;
    private javax.swing.JLabel lbDisneBanco;

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
        clienteController = new ClienteController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCpf = new javax.swing.JTextField();
        lbConta = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        pswSenha = new javax.swing.JPasswordField();
        bttLogin = new javax.swing.JButton();
        bttChamaViewsCadastro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 201, -1));

        lbConta.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbConta.setForeground(new java.awt.Color(255, 255, 255));
        lbConta.setText("CPF:");
        getContentPane().add(lbConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 201, -1));

        lbSenha.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbSenha.setForeground(new java.awt.Color(255, 255, 255));
        lbSenha.setText("Senha:");
        getContentPane().add(lbSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 201, -1));
        getContentPane().add(pswSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 201, -1));

        bttLogin.setText("Login");
        bttLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLoginActionPerformed(evt);
            }
        });
        getContentPane().add(bttLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 201, -1));

        bttChamaViewsCadastro.setText("Cadastrar");
        bttChamaViewsCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttChamaViewsCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(bttChamaViewsCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 201, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/a3 2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 10, 470, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/black-squares-pattern-background (1).jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 423, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttChamaViewsCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttChamaViewsCadastroActionPerformed
       
        FromCadastroView view = new FromCadastroView();
        view.setVisible(true); // Show the interface
        view.setLocationRelativeTo(null); // Center the interface on the screen

    }//GEN-LAST:event_bttChamaViewsCadastroActionPerformed

    private void bttLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLoginActionPerformed
        String cpf = txtCpf.getText();
        String senha = new String(pswSenha.getPassword());

        Cliente cliente = clienteController.autenticarCliente(cpf, senha);

        if (cliente != null) {
            // Buscar a conta correspondente ao cliente
            Conta conta = clienteController.buscarContaDoCliente(cliente);

            if (conta != null) {
                JOptionPane.showMessageDialog(this, "Login realizado com sucesso!");
                MenuView menuView = new MenuView();
                menuView.setCliente(cliente);
                menuView.setConta(conta); // Definir a conta na MenuView
                menuView.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Conta não encontrada para o cliente.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "CPF ou Senha inválidos.");
        }
    }//GEN-LAST:event_bttLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttChamaViewsCadastro;
    private javax.swing.JButton bttLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbConta;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JTextField txtCpf;
    // End of variables declaration//GEN-END:variables
}
