package View;

import controller.ContaController;
import model.Conta;
import javax.swing.JOptionPane;
import model.Cliente;

public class MenuView extends javax.swing.JFrame {

    private ContaController contaController;
    private Cliente cliente;
    private Conta conta; // Adicione isso para armazenar a conta atual
    private javax.swing.JTextField txtCpf; // Certifique-se de que txtCpf é o nome correto do campo de texto para CPF
    private javax.swing.JTextField jsaldoAtual; // Supondo que você tenha este campo para exibir o saldo

    public MenuView() {
        initComponents();
        contaController = new ContaController(); // Inicialize o controller
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
        setNumeroConta(cliente.getNumeroConta());
    }

    public void setConta(Conta conta) {
        this.conta = conta;
        if (conta != null) {
            txtConta.setText(String.valueOf(conta.getNumeroConta()));
            atualizarSaldo(conta.getSaldo());
        } else {
            txtConta.setText("Conta encontrada");
        }
    }

    public void setNumeroConta(int numeroConta) {
        Conta conta = contaController.buscarContaPorNumero(numeroConta);
        if (conta != null) {
            txtConta.setText(String.valueOf(conta.getNumeroConta()));
            atualizarSaldo(conta.getSaldo());
        } else {
            JOptionPane.showMessageDialog(this, "Conta encontrada.");
        }
    }

    // Método para atualizar o CPF no campo de texto
    public void setCpf(String cpf) {
        txtCpf.setText(cpf);
    }

    // Método para atualizar o saldo
    public void atualizarSaldo(double saldo) {
        txtSaldoconta.setText(String.format("%.2f", saldo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lbSacar = new javax.swing.JLabel();
        lbDepositar = new javax.swing.JLabel();
        jvalorADepositar = new javax.swing.JTextField();
        bttSair = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jvalorASacar = new javax.swing.JTextField();
        bttSacar = new javax.swing.JButton();
        bttDeposito = new javax.swing.JButton();
        lbConta = new javax.swing.JLabel();
        txtConta = new javax.swing.JTextField();
        txtSaldoconta = new javax.swing.JTextField();
        jLabel1saldo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbSacar.setText("Sacar:");

        lbDepositar.setText("Depositar:");

        jvalorADepositar.setText("0,00");

        bttSair.setText("Sair");
        bttSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSairActionPerformed(evt);
            }
        });

        jvalorASacar.setText("0,00");

        bttSacar.setText("Sacar");
        bttSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSacarActionPerformed(evt);
            }
        });

        bttDeposito.setText("Déposito");
        bttDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttDepositoActionPerformed(evt);
            }
        });

        lbConta.setText("Conta:");

        txtSaldoconta.setText("0,00");
        txtSaldoconta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldocontaActionPerformed(evt);
            }
        });

        jLabel1saldo.setText("Saldo:");
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbConta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jvalorADepositar, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(jvalorASacar)
                    .addComponent(txtConta))
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1saldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(bttSair, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bttSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(bttDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtSaldoconta, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lbConta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txtConta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jvalorASacar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jvalorADepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaldoconta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bttSair, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(bttSacar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSacarActionPerformed
        // TODO add your handling code here:
        if (conta == null) {
            JOptionPane.showMessageDialog(this, "Erro: Conta não inicializada.");
            return;
        }

        try {
            double valorSaque = Double.parseDouble(jvalorASacar.getText().replace(",", "."));
            boolean sucesso = conta.sacar(valorSaque);

            if (sucesso) {
                contaController.atualizarConta(conta);
                atualizarSaldo(conta.getSaldo());
                jvalorASacar.setText("0,00"); // Limpar campo após saque
                JOptionPane.showMessageDialog(this, "Valor sacado: " + valorSaque);
            } else {
                JOptionPane.showMessageDialog(this, "Saldo insuficiente.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um valor numérico válido para o saque.");
        }


    }//GEN-LAST:event_bttSacarActionPerformed

    private void bttDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttDepositoActionPerformed
        // TODO add your handling code here:
        if (txtConta.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, insira o número da conta.");
            return;
        }

        if (jvalorADepositar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, insira o valor a ser depositado.");
            return;
        }

        try {
            int numeroConta = Integer.parseInt(txtConta.getText());
            double valorDeposito = Double.parseDouble(jvalorADepositar.getText().replace(",", "."));

            Conta conta = contaController.buscarContaPorNumero(numeroConta);
            if (conta != null) {
                conta.depositar(valorDeposito);
                contaController.atualizarConta(conta);
                atualizarSaldo(conta.getSaldo());
                jvalorADepositar.setText("0,00"); // Limpar campo após depósito
                JOptionPane.showMessageDialog(this, "Valor depositado: " + valorDeposito);
            } else {
                JOptionPane.showMessageDialog(this, "Conta não encontrada.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, insira valores numéricos válidos para o número da conta e o valor do depósito.");
        }
    }//GEN-LAST:event_bttDepositoActionPerformed

    private void bttSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bttSairActionPerformed

    private void txtSaldocontaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldocontaActionPerformed
        // Obtém o número da conta do cliente
        int numeroConta = Integer.parseInt(txtConta.getText());

        // Busca a conta correspondente usando o ContaController
        Conta conta = contaController.buscarContaPorNumero(numeroConta);

        // Verifica se a conta foi encontrada
        if (conta != null) {
            // Atualiza o saldo no campo txtSaldoconta
            txtSaldoconta.setText(String.format("%.2f", conta.getSaldo()));
        } else {
            JOptionPane.showMessageDialog(this, "Conta não encontrada.");
        }
    }//GEN-LAST:event_txtSaldocontaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttDeposito;
    private javax.swing.JButton bttSacar;
    private javax.swing.JButton bttSair;
    private javax.swing.JLabel jLabel1saldo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jvalorADepositar;
    private javax.swing.JTextField jvalorASacar;
    private javax.swing.JLabel lbConta;
    private javax.swing.JLabel lbDepositar;
    private javax.swing.JLabel lbSacar;
    private javax.swing.JTextField txtConta;
    private javax.swing.JTextField txtSaldoconta;
    // End of variables declaration//GEN-END:variables
}
